# Generated by Django 4.2.7 on 2023-12-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_post_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="standout_image",
            field=models.ImageField(blank=True, null=True, upload_to="posts/"),
        ),
    ]
